apiVersion: apps/v1
kind: Deployment
metadata:
  name: buddy-get-fe
  labels:
    app: buddy-get-fe
spec:
  replicas: 3
  selector:
    matchLabels:
      app: buddy-get-fe
  template:
    metadata:
      labels:
        app: buddy-get-fe
    spec:
      containers:
        - name: buddy-get-fe
          image: buddy-get-fe:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: buddy-get-fe
spec:
  selector:
    app: buddy-get-fe
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80