apiVersion: apps/v1
kind: Deployment
metadata:
  name: buddy-get-be
  labels:
    app: buddy-get-be
spec:
  replicas: 3
  selector:
    matchLabels:
      app: buddy-get-be
  template:
    metadata:
      labels:
        app: buddy-get-be
    spec:
      containers:
        - name: buddy-get-be
          image: buddy-get-be:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: buddy-get-be
spec:
  selector:
    app: buddy-get-be
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080